#!/bin/bash
# This file takes a filename as argument and opens a yad file action dialog

script_name=$0


action=$(yad --width 300 --entry --title "Open with" \
    --image=ulauncher \
    --button="gtk-ok:0" --button="gtk-close:1" \
    --text "Choose application:" \
    --entry-text \
    "Default" "FileBrowser" "TextEditor" "ChooseApp")
ret=$?

[[ $ret -eq 1 ]] && exit 0

case $action in
    Default*) cmd="xdg-open \"${1}\"" ;;
    FileBrowser*) cmd="nautilus $1" ;;
    TextEditor*) cmd="gedit $1" ;;
    ChooseApp*) cmd="$(dirname "$0")/appchooser.py \"${1}\"" ;;
    *) exit 1 ;;    
esac

eval exec $cmd
